server:
  http:
    addr: 0.0.0.0:8080
    timeout: 10s
  grpc:
    addr: 0.0.0.0:9090
    timeout: 10s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/review_database?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
snowflake:
  start_time: "2025-04-19"
  machine_id: 1
registry:
  consul:
    address: 127.0.0.1:8500
    scheme: http